apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: helloworldapp
  namespace: {{ .Values.nameSpace }}
spec: 
  replicas: 2 
  selector: 
    matchLabels: 
      app: helloworldapp 
  template: 
    metadata: 
      labels: 
        app: helloworldapp 
    spec: 
      containers: 
      - name: helloworldapp 
        image: shayweitzman/helloworld
        ports: 
        - containerPort: 80
--- 

apiVersion: v1
kind: Service
metadata:
  name: helloworld-svc
  namespace: {{ .Values.nameSpace }}
spec: 
  ports:
  - protocol: TCP
    port: 80
    targetPort: 6565
  selector: 
    app: helloworldapp 